
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { DICTIONARY, AutomationTask } from '../types';
import { Play, Plus, Terminal, Code, Clock, CheckCircle, XCircle, Sparkles, X } from 'lucide-react';

export const AutomationView: React.FC = () => {
    const { automationTasks, runAutomationTask, addAutomationTask, language } = useApp();
    const t = DICTIONARY[language];
    
    const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
    const [newTask, setNewTask] = useState<Partial<AutomationTask>>({
        name: '',
        description: '',
        scriptType: 'PYTHON',
        script: ''
    });
    
    // AI Generation
    const [aiPrompt, setAiPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    const handleRun = (id: string) => {
        runAutomationTask(id);
    };

    const handleSave = () => {
        addAutomationTask(newTask);
        setIsCreateModalOpen(false);
        setNewTask({ name: '', description: '', scriptType: 'PYTHON', script: '' });
    };

    const generateScript = () => {
        if (!aiPrompt) return;
        setIsGenerating(true);
        // Simulate AI generation
        setTimeout(() => {
            const generated = `# Generated by NetGuardian AI for: ${aiPrompt}\nimport os\n\ndef main():\n    print("Starting automated task...")\n    # Logic for ${aiPrompt}\n    print("Success")\n\nif __name__ == "__main__":\n    main()`;
            setNewTask(prev => ({ ...prev, script: generated }));
            setIsGenerating(false);
        }, 1500);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center mb-6">
                <div>
                    <h2 className="text-2xl font-bold text-white">{t.automation}</h2>
                    <p className="text-slate-400 text-sm">Orchestrate and automate network operations with playbooks.</p>
                </div>
                <button 
                    onClick={() => setIsCreateModalOpen(true)}
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg transition-colors"
                >
                    <Plus size={18} /> New Playbook
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {automationTasks.map(task => (
                    <div key={task.id} className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between hover:border-blue-500/30 transition-all">
                        <div>
                            <div className="flex justify-between items-start mb-4">
                                <div className="p-3 bg-slate-800 rounded-lg">
                                    <Code size={24} className="text-purple-400" />
                                </div>
                                <span className="text-xs font-mono bg-slate-800 text-slate-300 px-2 py-1 rounded border border-slate-700">
                                    {task.scriptType}
                                </span>
                            </div>
                            <h3 className="text-lg font-bold text-slate-200 mb-2">{task.name}</h3>
                            <p className="text-sm text-slate-500 mb-6 h-10 overflow-hidden">{task.description}</p>
                        </div>

                        <div className="space-y-4">
                            <div className="flex items-center gap-2 text-xs text-slate-500">
                                <Clock size={12} />
                                Last Run: {task.lastRun ? task.lastRun.toLocaleString() : 'Never'}
                            </div>

                            {task.status === 'RUNNING' ? (
                                <div>
                                    <div className="flex justify-between text-xs text-blue-300 mb-1">
                                        <span>{t.running}</span>
                                        <span>{task.progress}%</span>
                                    </div>
                                    <div className="w-full bg-slate-800 h-2 rounded-full overflow-hidden">
                                        <div className="h-full bg-blue-500 transition-all duration-500" style={{ width: `${task.progress}%` }}></div>
                                    </div>
                                </div>
                            ) : (
                                <div className="flex items-center justify-between">
                                    {task.status === 'SUCCESS' && <span className="flex items-center gap-1 text-green-500 text-xs"><CheckCircle size={14}/> Success</span>}
                                    {task.status === 'FAILED' && <span className="flex items-center gap-1 text-red-500 text-xs"><XCircle size={14}/> Failed</span>}
                                    {task.status === 'IDLE' && <span></span>}
                                    
                                    <button 
                                        onClick={() => handleRun(task.id)}
                                        className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-blue-600 hover:text-white text-slate-300 rounded-lg transition-colors text-sm font-medium"
                                    >
                                        <Play size={14} /> {t.run}
                                    </button>
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Create Playbook Modal */}
            {isCreateModalOpen && (
                <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                    <div className="bg-slate-900 border border-slate-700 rounded-xl w-full max-w-2xl shadow-2xl p-6 max-h-[90vh] overflow-y-auto">
                        <div className="flex justify-between items-center mb-6">
                            <h3 className="text-xl font-bold text-white">Create New Playbook</h3>
                            <button onClick={() => setIsCreateModalOpen(false)} className="text-slate-400 hover:text-white"><X size={20}/></button>
                        </div>
                        
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm text-slate-400 mb-1">Playbook Name</label>
                                <input 
                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-2 text-white focus:outline-none focus:border-blue-500"
                                    value={newTask.name}
                                    onChange={e => setNewTask({...newTask, name: e.target.value})}
                                />
                            </div>
                            <div>
                                <label className="block text-sm text-slate-400 mb-1">Description</label>
                                <input 
                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-2 text-white focus:outline-none focus:border-blue-500"
                                    value={newTask.description}
                                    onChange={e => setNewTask({...newTask, description: e.target.value})}
                                />
                            </div>

                            {/* AI Generator Section */}
                            <div className="bg-blue-900/20 border border-blue-800/50 rounded-lg p-4">
                                <h4 className="text-sm font-bold text-blue-300 mb-2 flex items-center gap-2">
                                    <Sparkles size={14} /> AI Script Generator
                                </h4>
                                <div className="flex gap-2">
                                    <input 
                                        className="flex-1 bg-slate-950 border border-slate-700 rounded p-2 text-xs text-white"
                                        placeholder="e.g. Write a python script to backup cisco switch configs via SSH"
                                        value={aiPrompt}
                                        onChange={e => setAiPrompt(e.target.value)}
                                    />
                                    <button 
                                        onClick={generateScript}
                                        disabled={isGenerating}
                                        className="px-3 bg-blue-600 text-white rounded text-xs hover:bg-blue-500 disabled:opacity-50"
                                    >
                                        {isGenerating ? 'Generating...' : 'Generate'}
                                    </button>
                                </div>
                            </div>

                            <div>
                                <label className="block text-sm text-slate-400 mb-1">Script Type</label>
                                <select 
                                    className="w-full bg-slate-800 border border-slate-700 rounded-lg p-2 text-white focus:outline-none"
                                    value={newTask.scriptType}
                                    onChange={e => setNewTask({...newTask, scriptType: e.target.value as any})}
                                >
                                    <option value="PYTHON">Python</option>
                                    <option value="ANSIBLE">Ansible YAML</option>
                                    <option value="BASH">Bash Shell</option>
                                </select>
                            </div>

                            <div>
                                <label className="block text-sm text-slate-400 mb-1">Script Code</label>
                                <textarea 
                                    className="w-full h-40 bg-slate-950 border border-slate-700 rounded-lg p-3 text-green-400 font-mono text-xs focus:outline-none focus:border-blue-500"
                                    value={newTask.script}
                                    onChange={e => setNewTask({...newTask, script: e.target.value})}
                                ></textarea>
                            </div>

                            <div className="flex gap-3 pt-4">
                                <button onClick={() => setIsCreateModalOpen(false)} className="flex-1 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg">Cancel</button>
                                <button onClick={handleSave} className="flex-1 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg">Save Playbook</button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
