
import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { DICTIONARY, Report } from '../types';
import { FileBarChart, Download, FileText, Calendar, Loader2, X, Eye } from 'lucide-react';

export const ReportsView: React.FC = () => {
    const { language, reports, generateNewReport } = useApp();
    const t = DICTIONARY[language];
    const [generatingId, setGeneratingId] = useState<number | null>(null);
    const [previewReport, setPreviewReport] = useState<Report | null>(null);

    const reportTypes = [
        { id: 1, name: 'Network Uptime Summary', type: 'Uptime', desc: 'Monthly availability report for all core devices.', icon: <Calendar size={24} className="text-green-400"/> },
        { id: 2, name: 'Asset Inventory', type: 'Asset', desc: 'Complete list of hardware, IP addresses, and serial numbers.', icon: <FileText size={24} className="text-blue-400"/> },
        { id: 3, name: 'Security Audit Log', type: 'Security', desc: 'Detailed log of vulnerabilities and security patches.', icon: <FileBarChart size={24} className="text-red-400"/> },
    ];

    const handleGenerate = (id: number, type: string, name: string) => {
        setGeneratingId(id);
        generateNewReport(type, name);
        setTimeout(() => setGeneratingId(null), 1000); // UI feedback reset
    };

    const handleDownload = (report: Report) => {
        // Simulate a file download
        const content = `Report: ${report.name}\nDate: ${report.date}\nType: ${report.type}\n\nGenerated by NetGuardian AI.\nConfidential content.`;
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = report.name; // This will trigger a real browser download
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center mb-6">
                <div>
                    <h2 className="text-2xl font-bold text-white">{t.reports}</h2>
                    <p className="text-slate-400 text-sm">Generate and download system audits and performance summaries.</p>
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {reportTypes.map((report) => (
                    <div key={report.id} className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col justify-between hover:shadow-lg transition-shadow">
                        <div>
                            <div className="flex items-start justify-between mb-4">
                                <div className="p-3 bg-slate-800 rounded-lg">
                                    {report.icon}
                                </div>
                                <span className="bg-slate-800 text-slate-400 text-xs px-2 py-1 rounded">PDF / CSV</span>
                            </div>
                            <h3 className="text-lg font-bold text-slate-200 mb-2">{report.name}</h3>
                            <p className="text-sm text-slate-500 mb-6">{report.desc}</p>
                        </div>
                        
                        <div className="space-y-3">
                            <div>
                                <label className="text-xs text-slate-500 block mb-1">Time Range</label>
                                <select className="w-full bg-slate-800 border border-slate-700 rounded text-sm text-slate-300 p-2 focus:outline-none">
                                    <option>Last 24 Hours</option>
                                    <option>Last 7 Days</option>
                                    <option>Last 30 Days</option>
                                </select>
                            </div>
                            <button 
                                onClick={() => handleGenerate(report.id, report.type, report.name)}
                                disabled={generatingId === report.id}
                                className="w-full py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg flex items-center justify-center gap-2 text-sm font-medium transition-colors disabled:opacity-70 disabled:cursor-not-allowed"
                            >
                                {generatingId === report.id ? <Loader2 size={16} className="animate-spin"/> : <Download size={16} />}
                                {generatingId === report.id ? 'Processing...' : t.generateReport}
                            </button>
                        </div>
                    </div>
                ))}
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 mt-8">
                <h3 className="font-bold text-white mb-4">Recent Generated Reports</h3>
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left text-slate-400">
                        <thead className="text-xs text-slate-500 uppercase bg-slate-800/50">
                            <tr>
                                <th className="px-6 py-3">Report Name</th>
                                <th className="px-6 py-3">Date Generated</th>
                                <th className="px-6 py-3">Size</th>
                                <th className="px-6 py-3">Status</th>
                                <th className="px-6 py-3 text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-800">
                            {reports.map((report) => (
                                <tr key={report.id}>
                                    <td className="px-6 py-4 font-medium text-slate-200 flex items-center gap-2">
                                        <FileText size={16} className="text-slate-500"/>
                                        {report.name}
                                    </td>
                                    <td className="px-6 py-4">{report.date.toLocaleString()}</td>
                                    <td className="px-6 py-4">{report.size}</td>
                                    <td className="px-6 py-4">
                                        {report.status === 'GENERATING' ? (
                                            <span className="text-yellow-500 flex items-center gap-1 text-xs">
                                                <Loader2 size={12} className="animate-spin"/> Processing
                                            </span>
                                        ) : (
                                            <span className="text-green-400 text-xs bg-green-900/20 px-2 py-1 rounded border border-green-900/30">Ready</span>
                                        )}
                                    </td>
                                    <td className="px-6 py-4 text-right">
                                        {report.status === 'READY' && (
                                            <div className="flex justify-end gap-3">
                                                 <button onClick={() => setPreviewReport(report)} className="text-slate-400 hover:text-blue-400 transition-colors flex items-center gap-1 text-xs">
                                                    <Eye size={14}/> {t.preview}
                                                 </button>
                                                 <button onClick={() => handleDownload(report)} className="text-slate-400 hover:text-green-400 transition-colors flex items-center gap-1 text-xs">
                                                    <Download size={14}/> {t.download}
                                                 </button>
                                            </div>
                                        )}
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Preview Modal */}
            {previewReport && (
                <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
                    <div className="bg-slate-900 border border-slate-700 rounded-xl w-full max-w-4xl h-[80vh] flex flex-col shadow-2xl">
                        <div className="flex justify-between items-center p-4 border-b border-slate-800 bg-slate-800/50 rounded-t-xl">
                            <h3 className="font-bold text-white">{previewReport.name}</h3>
                            <button onClick={() => setPreviewReport(null)} className="text-slate-400 hover:text-white"><X size={24}/></button>
                        </div>
                        <div className="flex-1 bg-white p-8 overflow-y-auto">
                            {/* Simulated PDF Content */}
                            <div className="max-w-3xl mx-auto text-slate-900 font-serif">
                                <div className="text-center mb-10">
                                    <h1 className="text-3xl font-bold mb-2">NetGuardian AI Audit Report</h1>
                                    <p className="text-slate-500">Generated on {previewReport.date.toLocaleString()}</p>
                                </div>
                                <hr className="border-slate-300 mb-8"/>
                                <h2 className="text-xl font-bold mb-4">Executive Summary</h2>
                                <p className="mb-4 text-justify leading-relaxed">
                                    This report provides a comprehensive overview of the network infrastructure managed by NetGuardian AI. 
                                    During the reporting period, system stability remained at 99.9%. Security scanning identified minor vulnerabilities which are being addressed automatically.
                                </p>
                                <div className="grid grid-cols-2 gap-4 mb-8">
                                    <div className="p-4 bg-slate-100 rounded">
                                        <h4 className="font-bold text-sm mb-1">Total Assets</h4>
                                        <p className="text-2xl">25</p>
                                    </div>
                                    <div className="p-4 bg-slate-100 rounded">
                                        <h4 className="font-bold text-sm mb-1">Security Score</h4>
                                        <p className="text-2xl text-green-600">85/100</p>
                                    </div>
                                </div>
                                <p className="text-sm text-slate-400 text-center mt-20">Confidential Document - Internal Use Only</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
